### ISSUE TITLE
Tkinter 

### ISSUE THREAD

**Issue by MrKrishnaAgarwal** [MrKrishnaAgarwal/Hacktoberfest2022#23]
- Write a Program in Python using the **Tkinter** library which includes GUI. 

_If you want to work upon it, comment here and I'll assign it to you._

**Comment by PrakashGatiyala** [comment]
Hi @MrKrishnaAgarwal , I would like to work on this issue.

**Comment by MrKrishnaAgarwal** [comment]
> Hi @MrKrishnaAgarwal , I would like to work on this issue. 

Sure, All the best!
