### ISSUE TITLE
Adding other projects to work people upon in issues section 

### ISSUE THREAD

**Issue by Daksheshapkare** [MrKrishnaAgarwal/Hacktoberfest2022#33]
### What would you like to share?

Hey 
I just want you to request you to just add new and more innovative ideas in issues section
So people can work upon and to assign

**Comment by MrKrishnaAgarwal** [comment]
Okay Sure!
I'll do that 😇

**FunFact: you can also open issues of the projects or code you want to work upon. **

**Comment by MrKrishnaAgarwal** [comment]
Okay Sure!
I'll do that 😇

**FunFact: you can also open issues of the projects or code you want to work upon. **

If you know anything open the issue for it and make a pull request, You can contribute how you like and according to what you know too and definitely I'll add more issues.
